{% set name = "cyminmax" %}
{% set version = "0.1.1" %}
{% set checksum = "cb448c88499a394a15fd24d9344115bd806dfc8d28a1981d5e1626094dbbc40b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools >=18.0
    - cython >=0.25.2
    - numpy >=1.11.3,<1.12

  run:
    - python
    - numpy >=1.11

test:
  source_files:
    - tests

  imports:
    - cyminmax

  requires:
    - pytest

  commands:
    - pytest

about:
  home: https://github.com/jakirkham/cyminmax
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: A minmax implementation in Cython for use with NumPy
  doc_url: https://cyminmax.readthedocs.io/
  dev_url: https://github.com/jakirkham/cyminmax

extra:
  recipe-maintainers:
    - jakirkham
