travis:
  secure:
    BINSTAR_TOKEN: VVLeuJidbrEOt2A91k0ya+G+VWIFARhuNV9H7u2JZmp92wzkOcbfMl8a9OAJdKhF8/jQmIcTQGuJc2T8lnDqpv0uRMSBWoQq0wrEUjZkpI1cTLIhG+J96Q+8VO9x5d486uEaYEGsUn/eAO/fJX+/+HRksCQaPCZ4Omfa7RuX8AffX0yF3GURNpN4ejbzwV/5jeHXBXjthlocrvR+wnFrQnN/qJ8ZnLy6KddRJJ+2AhvugbPyUAKRpqsNlX9OMmdX1cclo7gLke2dswdfIv2s4AFNLBAC+960NWf/xcFwENmI2YwP62xcp3R6LYc24Gqx9xFSOJ0/52I+MVS50KdhX91bSfrEVijJLgQIfsuaOxBkYn4pbdBhJpZdI3pAeIOzcQIdDdSBbRk68pyjfO2wCXXdPviIBHoN/NWhdWY2WzR4P6kJpUY026zZ9mKH+sTkdBsZkyGidfypD8FCm21kJWJ45OZrmeEleBBtXJ6BmUmDL/R/8v6B43iYd2dN21vqvWQK6GrTGdg4/nRkbfODOyOJRfzPGHW0ut4/CQhMGRy5x05qO+SaqZ95qAnkySLKbGXJSpWSB87PK1trAS2kLBo//zrmN3FNsG3imlO38aqedkzH9fdTghYCYyHlD2TjoB+X1pcEDcAYAFzfwK+HjWifphfuwWTFJB/UNI7atXw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
